// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.ProgressBars {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("ProgressBars_iPhone")]
	public partial class ProgressBars_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIProgressView __mt_btnProgress1;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnProgress1")]
		private UIKit.UIProgressView btnProgress1 {
			get {
				this.__mt_btnProgress1 = ((UIKit.UIProgressView)(this.GetNativeField("btnProgress1")));
				return this.__mt_btnProgress1;
			}
			set {
				this.__mt_btnProgress1 = value;
				this.SetNativeField("btnProgress1", value);
			}
		}
	}
}
