//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWC
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int grey = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lightgrey = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int white = 2130968579;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int favorite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int favorited = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_about = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tab_exhibitors = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tab_favorites = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tab_maps = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tab_rss = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_schedule = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tab_schedule_unselected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tab_sessions = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tab_speakers = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tab_twitter = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int AboutButton = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int AboutTextView = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int BigTextView = 2131165195;
			
			// aapt resource value: 0x7f070020
			public const int Bio = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int CompanyTextView = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int ContentTextView = 2131165221;
			
			// aapt resource value: 0x7f070015
			public const int ContentWebView = 2131165205;
			
			// aapt resource value: 0x7f070005
			public const int CountryTextView = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int DateTimeTextView = 2131165208;
			
			// aapt resource value: 0x7f07000e
			public const int DayList = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int DescriptionTextView = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int ExhibitorImageView = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int ExhibitorList = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int ExhibitorsButton = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int FavoritesButton = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int FavoritesList = 2131165194;
			
			// aapt resource value: 0x7f07001a
			public const int FavouriteButton = 2131165210;
			
			// aapt resource value: 0x7f070024
			public const int HandleTextView = 2131165220;
			
			// aapt resource value: 0x7f070006
			public const int LocationTextView = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int NameTextView = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int NewsButton = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int NewsList = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int OverviewTextView = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int PositionTextView = 2131165214;
			
			// aapt resource value: 0x7f070014
			public const int PublishedTextView = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int RoomTextView = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int SessionList = 2131165212;
			
			// aapt resource value: 0x7f07000c
			public const int SmallTextView = 2131165196;
			
			// aapt resource value: 0x7f07001d
			public const int SpeakerImageView = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int SpeakerList = 2131165217;
			
			// aapt resource value: 0x7f070017
			public const int SpeakersTextView = 2131165207;
			
			// aapt resource value: 0x7f070023
			public const int TimeTextView = 2131165219;
			
			// aapt resource value: 0x7f070008
			public const int TitleTextView = 2131165192;
			
			// aapt resource value: 0x7f070026
			public const int TweetList = 2131165222;
			
			// aapt resource value: 0x7f070010
			public const int TwitterButton = 2131165200;
			
			// aapt resource value: 0x7f070022
			public const int TwitterImageView = 2131165218;
			
			// aapt resource value: 0x7f070000
			public const int about = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int home = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int scroller = 2131165186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutXamScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExhibitorDetailsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExhibitorListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExhibitorsScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FavoritesScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GenericListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HomeListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HomeScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MoreScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewsDetailsScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int NewsListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int NewsScreen = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SessionDetailsScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SessionListItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SessionsScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SessionTimeslotListItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SpeakerDetailsScreen = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SpeakerListItem = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SpeakersScreen = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int TabBar = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int TweetDetailsScreen = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TwitterListItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int TwitterScreen = 2130903062;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int AboutXamarin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomTheme = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
