//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWC
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MWCLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int XamLogo = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int BigTextView = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int Bio = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int Brief = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int ContentTextView = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int DateTimeDisplay = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int DayList = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ExhibitorList = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int FavouriteButton = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int LocationTextView = 2131034116;
			
			// aapt resource value: 0x7f050015
			public const int Name = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int NameTextView = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int NewsList = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int PublishedTextView = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int Room = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int SessionList = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int SmallTextView = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int SpeakerList = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int Title = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int TitleTextView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int logo = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int mwclogo = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int scroller = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int xamlogo = 2131034120;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutXamScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExhibitorDetailsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExhibitorsScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NewsDetailsScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewsListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewsScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SessionDetailsScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SessionsScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SpeakerDetailsScreen = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SpeakersScreen = 2130903052;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
