//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWC
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MWCLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int XamLogo = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int BigTextView = 2131099654;
			
			// aapt resource value: 0x7f060017
			public const int Bio = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int CompanyTextView = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int ContentTextView = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int DateTimeTextView = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int DayList = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int ExhibitorList = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int FavouriteButton = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int LocationTextView = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int Name = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int NameTextView = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int NewsList = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int OverviewTextView = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int PublishedTextView = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int RoomTextView = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int SessionList = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int SmallTextView = 2131099655;
			
			// aapt resource value: 0x7f060018
			public const int SpeakerList = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int SpeakersTextView = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int Title = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int TitleTextView = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int logo = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int mwclogo = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int scroller = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int xamlogo = 2131099657;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutXamScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExhibitorDetailsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExhibitorsScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GenericListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HomeScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewsDetailsScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewsListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewsScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionDetailsScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SessionListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SessionsScreen = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SessionTimeslotListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SpeakerDetailsScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SpeakersScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TweetDetailsScreen = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TwitterListItem = 2130903056;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int CustomTheme = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int CustomWindowTitleBackground = 2130968576;
			
			private Style()
			{
			}
		}
	}
}
