// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.Sliders {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("Sliders_iPhone")]
	public partial class Sliders_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UISlider __mt_sldrWithImages;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("sldrWithImages")]
		private UIKit.UISlider sldrWithImages {
			get {
				this.__mt_sldrWithImages = ((UIKit.UISlider)(this.GetNativeField("sldrWithImages")));
				return this.__mt_sldrWithImages;
			}
			set {
				this.__mt_sldrWithImages = value;
				this.SetNativeField("sldrWithImages", value);
			}
		}
	}
}
