#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StandardControls.Resource", IsApplication=true)]

namespace StandardControls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int listseparator = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int red = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int yellow = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int seekbar_margin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Beach = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Beach_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Calendar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_artists = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_artists_grey = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_artists_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int imagebutton_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Plants = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Seeds = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Shanghai = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int AutoCompleteInput = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ComplexAlertButton = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int ContextMenuText = 2131165190;
			
			// aapt resource value: 0x7f070020
			public const int CustomToastButton = 2131165216;
			
			// aapt resource value: 0x7f070009
			public const int Frame = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Gallery = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Grid = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int ImageButton = 2131165188;
			
			// aapt resource value: 0x7f07001e
			public const int LongToastButton = 2131165214;
			
			// aapt resource value: 0x7f07000c
			public const int Menu = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int NormalButton = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int ProgressBar = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int ProgressCircle = 2131165200;
			
			// aapt resource value: 0x7f07001d
			public const int ShortToastButton = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int SimpleAlertButton = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int Spinner = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int StyledTextView = 2131165210;
			
			// aapt resource value: 0x7f07000d
			public const int Text1 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int Text2 = 2131165199;
			
			// aapt resource value: 0x7f070021
			public const int ToastLayout = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int ToastText = 2131165218;
			
			// aapt resource value: 0x7f070005
			public const int ToggleButton = 2131165189;
			
			// aapt resource value: 0x7f07001f
			public const int TopToastButton = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int custombutton = 2131165219;
			
			// aapt resource value: 0x7f070007
			public const int dateDisplay = 2131165191;
			
			// aapt resource value: 0x7f070014
			public const int entry = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int label = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int ok = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int pickDate = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int pickTime = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int radio_blue = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int radio_red = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int seekBar1 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int textView1 = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int timeDisplay = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int urlTextView = 2131165209;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alert = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AutoCompleteTextView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Button = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CheckBox = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ContextMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DatePickerDialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EditText = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FrameLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Gallery = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int GridView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Home = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int HomeSectionHeader = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int HorizontalLinearLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int HorizontalLinearLayoutWeight = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int HorizontalScrollView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ImageView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LinearLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LinearLayoutWeight = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int OptionsMenu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ProgressBar = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ProgressDialog = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int RadioGroup = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int RatingBar = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int RelativeLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ScrollView = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SeekBarScreen = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Spinner = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int TabLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int TableLayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int TextView = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int TimePickerDialog = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Toast = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int ToastCustom = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
