// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.DatePicker {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("DatePickerSimple_iPhone")]
	public partial class DatePickerSimple_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UILabel __mt_lblDate;
		
		private UIKit.UIDatePicker __mt_pkrDate;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("lblDate")]
		private UIKit.UILabel lblDate {
			get {
				this.__mt_lblDate = ((UIKit.UILabel)(this.GetNativeField("lblDate")));
				return this.__mt_lblDate;
			}
			set {
				this.__mt_lblDate = value;
				this.SetNativeField("lblDate", value);
			}
		}
		
		[Foundation.Connect("pkrDate")]
		private UIKit.UIDatePicker pkrDate {
			get {
				this.__mt_pkrDate = ((UIKit.UIDatePicker)(this.GetNativeField("pkrDate")));
				return this.__mt_pkrDate;
			}
			set {
				this.__mt_pkrDate = value;
				this.SetNativeField("pkrDate", value);
			}
		}
	}
}
