// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DataAccess
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int NameLabel = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int NotesLabel = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int TaskDetailsHeader = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int btnAddTask = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int btnCancelDelete = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnSave = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int lstTasks = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int txtName = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int txtNotes = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskDetails = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
