// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using Foundation;
using UIKit;

namespace DataAccess
{
	public partial class StockDetailViewController : UITableViewController
	{
		public StockDetailViewController (IntPtr handle) : base (handle)
		{
		}

		Stock currentStock { get; set; }

		public RootViewController Delegate {get;set;}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SaveButton.TouchUpInside += (sender, e) => {
				currentStock.Name = Name.Text;
				currentStock.Symbol = Code.Text;

				Delegate.SaveStock(currentStock);
			};
			DeleteButton.TouchUpInside += (sender, e) => {
				if (currentStock == null) return;
				Delegate.DeleteStock(currentStock);
			};
		}
		
		// this will be called before the view is displayed 
		public void SetStock (RootViewController d, Stock Stock) {
			Delegate = d;
			currentStock = Stock;
		}
		// when displaying, set-up the properties
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			if (currentStock == null) currentStock = new Stock();;
			Name.Text = currentStock.Name;
			Code.Text = currentStock.Symbol;
		}
	}
}
