// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.Toolbar {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("Toolbar1_iPhone")]
	public partial class Toolbar1_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIBarButtonItem __mt_btnFour;
		
		private UIKit.UIBarButtonItem __mt_btnOne;
		
		private UIKit.UIBarButtonItem __mt_btnThree;
		
		private UIKit.UIBarButtonItem __mt_btnTwo;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnFour")]
		private UIKit.UIBarButtonItem btnFour {
			get {
				this.__mt_btnFour = ((UIKit.UIBarButtonItem)(this.GetNativeField("btnFour")));
				return this.__mt_btnFour;
			}
			set {
				this.__mt_btnFour = value;
				this.SetNativeField("btnFour", value);
			}
		}
		
		[Foundation.Connect("btnOne")]
		private UIKit.UIBarButtonItem btnOne {
			get {
				this.__mt_btnOne = ((UIKit.UIBarButtonItem)(this.GetNativeField("btnOne")));
				return this.__mt_btnOne;
			}
			set {
				this.__mt_btnOne = value;
				this.SetNativeField("btnOne", value);
			}
		}
		
		[Foundation.Connect("btnThree")]
		private UIKit.UIBarButtonItem btnThree {
			get {
				this.__mt_btnThree = ((UIKit.UIBarButtonItem)(this.GetNativeField("btnThree")));
				return this.__mt_btnThree;
			}
			set {
				this.__mt_btnThree = value;
				this.SetNativeField("btnThree", value);
			}
		}
		
		[Foundation.Connect("btnTwo")]
		private UIKit.UIBarButtonItem btnTwo {
			get {
				this.__mt_btnTwo = ((UIKit.UIBarButtonItem)(this.GetNativeField("btnTwo")));
				return this.__mt_btnTwo;
			}
			set {
				this.__mt_btnTwo = value;
				this.SetNativeField("btnTwo", value);
			}
		}
	}
}
