// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TipCalc.UI.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ReceiptTotal = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Subtotal = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int TipPercent = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int TipPercentSeekbar = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int TipValue = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Total = 2131034117;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
