#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinTodoQuickStart.Resource", IsApplication=true)]

namespace XamarinTodoQuickStart
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ByteSmith.WindowsAzure.Messaging.Resource.String.library_name = global::XamarinTodoQuickStart.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::XamarinTodoQuickStart.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int buttonAddTodo = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int checkTodoItem = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int listViewTodo = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int loadingProgressBar = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int menu_refresh = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int textNewTodo = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_To_Do = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Row_List_To_Do = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int add_button_text = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int add_textbox_hint = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int checkbox_text = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int menu_refresh = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int mobile_services = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
