// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Reflection;

namespace EmbeddedResources
{
	public partial class HomeScreen : UIViewController
	{
		public HomeScreen (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();


			string haikuText = ResourceLoader.GetEmbeddedResourceString (Assembly.GetAssembly(typeof(ResourceLoader)), "ALittleStory.txt");

			this.HaikuTextView.Text = haikuText;
		}
	}
}
