#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.xamarin.evolve2013.animationsdemo.Resource", IsApplication=true)]

namespace com.xamarin.evolve2013.animationsdemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int hyperspace = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asteroid01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int asteroid02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int asteroid03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int asteroid04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int asteroid05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int asteroid06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_info = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_new = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_photo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_list_remove = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int image1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int image2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shape_oval_purple_gradient = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int shape_rounded_blue_rect = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ship2_2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int spinning_asteroid = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int thumb1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int thumb2 = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int container = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int expanded_image = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int frameLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int karmaMeter = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int karmaSeeker = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int thumb_button_1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int thumb_button_2 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_drawing = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_imageandbutton = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_propertyanimation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_shapedrawable = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_zoom = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int description_image_1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int description_image_2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int description_zoom_touch_close = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int message_shapedrawable = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int message_zoom_touch_expand = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int title_animationdrawable = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int title_drawing = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int title_hyperspace = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int title_propertyanimation = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int title_setkarma = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int title_shapedrawables = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int title_spinasteroid = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int title_viewanimation = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int title_zoom = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
