// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_ContentControls.Screens.iPhone.CustomizingNavBar {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("CustomizingNavBarScreen")]
	public partial class CustomizingNavBarScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnChangeBarStyle;
		
		private UIKit.UIButton __mt_btnChangeTintColor;
		
		private UIKit.UIButton __mt_btnShowHideRightButton;
		
		private UIKit.UISwitch __mt_swchTransparent;
		
		private UIKit.UIButton __mt_btnShowToolbar;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnChangeBarStyle")]
		private UIKit.UIButton btnChangeBarStyle {
			get {
				this.__mt_btnChangeBarStyle = ((UIKit.UIButton)(this.GetNativeField("btnChangeBarStyle")));
				return this.__mt_btnChangeBarStyle;
			}
			set {
				this.__mt_btnChangeBarStyle = value;
				this.SetNativeField("btnChangeBarStyle", value);
			}
		}
		
		[Foundation.Connect("btnChangeTintColor")]
		private UIKit.UIButton btnChangeTintColor {
			get {
				this.__mt_btnChangeTintColor = ((UIKit.UIButton)(this.GetNativeField("btnChangeTintColor")));
				return this.__mt_btnChangeTintColor;
			}
			set {
				this.__mt_btnChangeTintColor = value;
				this.SetNativeField("btnChangeTintColor", value);
			}
		}
		
		[Foundation.Connect("btnShowHideRightButton")]
		private UIKit.UIButton btnShowHideRightButton {
			get {
				this.__mt_btnShowHideRightButton = ((UIKit.UIButton)(this.GetNativeField("btnShowHideRightButton")));
				return this.__mt_btnShowHideRightButton;
			}
			set {
				this.__mt_btnShowHideRightButton = value;
				this.SetNativeField("btnShowHideRightButton", value);
			}
		}
		
		[Foundation.Connect("swchTransparent")]
		private UIKit.UISwitch swchTransparent {
			get {
				this.__mt_swchTransparent = ((UIKit.UISwitch)(this.GetNativeField("swchTransparent")));
				return this.__mt_swchTransparent;
			}
			set {
				this.__mt_swchTransparent = value;
				this.SetNativeField("swchTransparent", value);
			}
		}
		
		[Foundation.Connect("btnShowToolbar")]
		private UIKit.UIButton btnShowToolbar {
			get {
				this.__mt_btnShowToolbar = ((UIKit.UIButton)(this.GetNativeField("btnShowToolbar")));
				return this.__mt_btnShowToolbar;
			}
			set {
				this.__mt_btnShowToolbar = value;
				this.SetNativeField("btnShowToolbar", value);
			}
		}
	}
}
