#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GeolocationSample.Resource", IsApplication=true)]

namespace GeolocationSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int cancelPositionButton = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int getPositionButton = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int lAccuracy = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int lLatitude = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int lLongitude = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int listenStatus = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int pAccuracy = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int pLatitude = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int pLongitude = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int status = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int toggleListeningButton = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int cancelPosition = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int getPosition = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int startListening = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int stopListening = 2130968579;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
