#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Tasky.Droid.Resource", IsApplication=true)]

namespace Tasky.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_addtask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_checkmark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int NameLabel = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int NotesLabel = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int checkMark = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int checkmark = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int chkDone = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int lblDescription = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int lblName = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int lstTasks = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int menu_add_task = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int menu_delete_task = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int menu_save_task = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int txtName = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int txtNotes = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_detailsscreen = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_homescreen = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
