// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MWC.iOS.Screens.Common.Twitter {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("TwitterDetailViewController")]
	public partial class TwitterDetailViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextView __mt_tweet;
		
		private MonoTouch.UIKit.UIImageView __mt_image;
		
		private MonoTouch.UIKit.UILabel __mt_user;
		
		private MonoTouch.UIKit.UILabel __mt_date;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tweet")]
		private MonoTouch.UIKit.UITextView tweet {
			get {
				this.__mt_tweet = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("tweet")));
				return this.__mt_tweet;
			}
			set {
				this.__mt_tweet = value;
				this.SetNativeField("tweet", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("image")]
		private MonoTouch.UIKit.UIImageView image {
			get {
				this.__mt_image = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("image")));
				return this.__mt_image;
			}
			set {
				this.__mt_image = value;
				this.SetNativeField("image", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("user")]
		private MonoTouch.UIKit.UILabel user {
			get {
				this.__mt_user = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("user")));
				return this.__mt_user;
			}
			set {
				this.__mt_user = value;
				this.SetNativeField("user", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("date")]
		private MonoTouch.UIKit.UILabel date {
			get {
				this.__mt_date = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("date")));
				return this.__mt_date;
			}
			set {
				this.__mt_date = value;
				this.SetNativeField("date", value);
			}
		}
	}
}
