// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_ContentControls.Screens.iPhone.Browsers {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("WebBrowser")]
	public partial class WebBrowser {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnBack;
		
		private UIKit.UIButton __mt_btnForward;
		
		private UIKit.UIButton __mt_btnGo;
		
		private UIKit.UIButton __mt_btnStop;
		
		private UIKit.UITextField __mt_txtAddress;
		
		private UIKit.UIWebView __mt_webMain;
		
		private UIKit.UIActivityIndicatorView __mt_imgBusy;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnBack")]
		private UIKit.UIButton btnBack {
			get {
				this.__mt_btnBack = ((UIKit.UIButton)(this.GetNativeField("btnBack")));
				return this.__mt_btnBack;
			}
			set {
				this.__mt_btnBack = value;
				this.SetNativeField("btnBack", value);
			}
		}
		
		[Foundation.Connect("btnForward")]
		private UIKit.UIButton btnForward {
			get {
				this.__mt_btnForward = ((UIKit.UIButton)(this.GetNativeField("btnForward")));
				return this.__mt_btnForward;
			}
			set {
				this.__mt_btnForward = value;
				this.SetNativeField("btnForward", value);
			}
		}
		
		[Foundation.Connect("btnGo")]
		private UIKit.UIButton btnGo {
			get {
				this.__mt_btnGo = ((UIKit.UIButton)(this.GetNativeField("btnGo")));
				return this.__mt_btnGo;
			}
			set {
				this.__mt_btnGo = value;
				this.SetNativeField("btnGo", value);
			}
		}
		
		[Foundation.Connect("btnStop")]
		private UIKit.UIButton btnStop {
			get {
				this.__mt_btnStop = ((UIKit.UIButton)(this.GetNativeField("btnStop")));
				return this.__mt_btnStop;
			}
			set {
				this.__mt_btnStop = value;
				this.SetNativeField("btnStop", value);
			}
		}
		
		[Foundation.Connect("txtAddress")]
		private UIKit.UITextField txtAddress {
			get {
				this.__mt_txtAddress = ((UIKit.UITextField)(this.GetNativeField("txtAddress")));
				return this.__mt_txtAddress;
			}
			set {
				this.__mt_txtAddress = value;
				this.SetNativeField("txtAddress", value);
			}
		}
		
		[Foundation.Connect("webMain")]
		private UIKit.UIWebView webMain {
			get {
				this.__mt_webMain = ((UIKit.UIWebView)(this.GetNativeField("webMain")));
				return this.__mt_webMain;
			}
			set {
				this.__mt_webMain = value;
				this.SetNativeField("webMain", value);
			}
		}
		
		[Foundation.Connect("imgBusy")]
		private UIKit.UIActivityIndicatorView imgBusy {
			get {
				this.__mt_imgBusy = ((UIKit.UIActivityIndicatorView)(this.GetNativeField("imgBusy")));
				return this.__mt_imgBusy;
			}
			set {
				this.__mt_imgBusy = value;
				this.SetNativeField("imgBusy", value);
			}
		}
	}
}
