// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_ContentControls.Screens.iPhone.ExtraScreens {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("CustomizableTabScreen")]
	public partial class CustomizableTabScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UILabel __mt_lblNumber;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("lblNumber")]
		private UIKit.UILabel lblNumber {
			get {
				this.__mt_lblNumber = ((UIKit.UILabel)(this.GetNativeField("lblNumber")));
				return this.__mt_lblNumber;
			}
			set {
				this.__mt_lblNumber = value;
				this.SetNativeField("lblNumber", value);
			}
		}
	}
}
